### ISSUE TITLE
Polygons missing from the model

### ISSUE THREAD

**Issue by skeswa** [CodyJamesCasey/ghost-pepper#1]
Weird rendering problem where pieces of the model don't show up.

**Comment by CodyJamesCasey** [comment]
doesn't seem to happen on all models. I've tried a bunch from http://webgl-tests.crbs.ucsd.edu/obj-viewer/ and most of them that have obj and mtl files turn out with no missing polygons

**Comment by YurkaninRyan** [comment]
Yeah this definitely has to do with the obj file, I vote to close this
